spring:
  application:
    name: spring-boot-mvc
  jpa:
    generate-ddl: true
  datasource:
    name: fileUpload
  http:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB
server:
  port: 8080